#!/usr/bin/python

import os
homedir = os.path.expanduser("~")
include_dir = [ homedir + '/github/netlib/',
                homedir + '/github/netlib/http_client',
                homedir + '/github/netlib/netutils',
                homedir + '/tools/zlib/include', 
                homedir + '/tools/log4c/include', 
                homedir + '/github/program/common'
                ]


env = Environment(CPPPATH = [include_dir], CCFLAGS = '-g')

test_sources = [str(fn) for fn in Glob('*.cpp')]

libsname=[
     'netlib',
     'pthread'
]

for file in test_sources:
    env.Program(file[0:file.find(".cpp")], [file], LIBPATH=["../build"], LIBS=libsname)

