#
Import('include_dir')

env = Environment(CPPPATH = [include_dir], CCFLAGS = '-g')

test_sources = [str(fn) for fn in Glob('*.cpp')]

libsname=[
     'netlib',
     'pthread'
]

# for file in test_sources:
#     env.Program(file[0:file.find(".cpp")], [file], LIBPATH=[".."], LIBS=libsname)

