#!/usr/bin/python

Import("cflags")
Import("include_dir")

env = Environment(CPPPATH = include_dir, CCFLAGS = cflags, tools=['default', 'packaging'])

libsname=[
     'netlib',
     'z',
     'common',
     'log4c',
     'pthread'
]

lib_path=['/home/dyc/github/netlib/build',
          '/home/dyc/github/program/common',
          '/home/dyc/tools/log4c/lib',
          '/home/dyc/tools/zlib/lib']

for prog in [str(fn) for fn in Glob('*.cpp')] : 
    env.Program(prog[0:-4], [prog], LINKFLAGS="", LIBPATH=lib_path, LIBS=libsname)


# env.Program("http_client", ["http_client.cpp"], LINKFLAGS="", LIBPATH=lib_path, LIBS=libsname)
# 
# env.Program("trival_server", ["trival_server.cpp"], LINKFLAGS="", LIBPATH=lib_path, LIBS=libsname)

