#!/usr/bin/python

Import("cflags")
Import("include_dir")

env = Environment(CPPPATH = include_dir, CCFLAGS = cflags, tools=['default', 'packaging'])

libsname=[
     'netlib',
     'z',
     'common',
     'log4c',
     'pthread'
]

lib_path=['/home/dyc/github/program/netlib/net_client/tools', 
          '/home/dyc/github/program/netlib/net_client/build',
          '/home/dyc/github/program/common',
          '/home/dyc/tools/log4c/lib',
          '/home/dyc/tools/zlib']

main = env.Program("main", ["main.cpp"], LINKFLAGS="", LIBPATH=lib_path, LIBS=libsname)

