#!/usr/bin/python

Import("include_dir")
cflags="-g "

env = Environment(CPPPATH = include_dir, CCFLAGS = cflags, tools=['default', 'packaging'])


tools_sources = [str(fn) for fn in Glob('*.cpp') if str(fn) not in ['main.cpp']]

env.Library(target = 'tools', source = tools_sources, dirInPackage = 'lib64')

