
netlib_sources = [str(fn) for fn in Glob('*.cpp') if str(fn) not in ['main.cpp']]

env = Environment(CPPPATH = ['.'], CCFLAGS = '-g')

env.Library(target = 'netlib',
             source = netlib_sources,
             dirInPackage = 'lib64')



libsname=[
     'netlib',
     'pthread'
]


Repository('/home/dingyc/tools/zlib')
env.Program("main", ["main.cpp"], LIBPATH=["."], LIBS=["netlib"])

